### ISSUE TITLE
Publish on deno.land/x

### ISSUE THREAD

**Issue by JumpLink** [lumeland/pug#2]
I found the module later because it is not on deno.land/x. I think it would be used by more people if you would publish it there.

**Comment by oscarotero** [comment]
I didn't publish it because I was hoping the oficial Pug team would bring support for Deno at some point and I didn't want to use the `pug` name in deno.land (although I now see somebody used it).
Maybe I can publish as `pug-deno` or something like that.

**Comment by JumpLink** [comment]
ah okay i see, then let's wait and see

Yes pug on deno.land/x is a wrapper for node-pug: https://deno.land/x/pug@v0.1.3 which also works without code changes on deno, but native support is much nicer ;)
